[package]
name = "impl-borsh"
version = "0.1.0"
description = "Borsh serialization support for uint and fixed hash."
edition = "2021"

[features]
default = ["std"]
std = ["borsh/std"]

[dependencies]
borsh = { version = "0.9.3", default-features = false }
